#运行端口
server:
  port: 8090
  http2:
    enabled: true
  undertow:
    url-charset: UTF-8
    io-threads: 8
    worker-threads: 64
    buffer-size: 1024
    direct-buffers: true
    max-http-post-size: 1000
    eager-filter-init: true

#应用全局设置
app:
  env: LOCAL
  #服务端点
  endpoint:
    account-service-endpoint: http://localhost:8089
    company-service-endpoint: http://localhost:8090
    bot-service-endpoint: http://localhost:8091
  #线程池
  async-thread-pool:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 100
    wait-for-tasks-complete: true
    keep-alive: 60
    thread-prefix-name: BenAsyncThread-

spring:
  application:
    name: company-svc
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
  data:
    mongodb:
      uri: mongodb://localhost:27017/ben
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: ben-elasticsearch
      cluster-nodes: 127.0.0.1:9300
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000
  cloud:
    alibaba:
      seata:
        tx-service-group: ben-tx-group
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ben_company?useUnicode=true&characterEncoding=utf8&&autoReconnect=true&useSSL=false&&serverTimezone=CTT
    username: root
    password: lomofu
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      exception-sorter: true
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        login-username: admin
        login-password: lomofu
  #    hikari:
  #      driver-class-name: com.mysql.cj.jdbc.Driver
  #      minimum-idle: 5
  #      maximum-pool-size: 15
  #      auto-commit: true
  #      idle-timeout: 30000
  #      pool-name: DatebookHikariCP
  #      max-lifetime: 1800000
  #      connection-timeout: 3000
  #      connection-test-query: SELECT 1
  servlet:
    multipart:
      file-size-threshold: 10485760
      max-file-size: 1MB
  mvc:
    throw-exception-if-no-handler-found: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ben.company.entity


mapper:
  not-empty: false

pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

logging:
  level:
    i:
      l:
        core:
          protocol:
            ReconnectionHandler: error
            ConnectionWatchdog: error