#运行端口
server:
  port: 8080
  http2:
    enabled: true
  undertow:
    url-charset: UTF-8
    io-threads: ${UNDERTOW_IO_THREADS:4}
    worker-threads: ${UNDERTOW_WORKER_THREADS:8}
    buffer-size: ${UNDERTOW_BUFFER_SIZE:1024}
    direct-buffers: true
    eager-filter-init: true
    max-http-post-size: ${UNDERTOW_MAX_POST:1000}

#应用全局设置
app:
  env: DEV
  #服务端点
  endpoint:
    account-service-endpoint: ${ACCOUNT_SERVICE_ENDPOINT}
    bot-service-endpoint: ${BOT_SERVICE_ENDPOINT}
    company-service-endpoint: ${COMPANY_SERVICE_ENDPOINT}
  #线程池
  async-thread-pool:
    core-pool-size: ${ASYNC_CORE_POOL:10}
    max-pool-size: ${ASYNC_MAX_POOL:30}
    queue-capacity: ${ASYNC_QUEUE_CAPACITY:100}
    wait-for-tasks-complete: ${ASYNC_WAIT_FOR_COMPLETE:true}
    keep-alive: ${ASYNC_KEEP_ALIVE:60}
    thread-prefix-name: BenAsyncThread-
  #oss服务器
  oss:
    endpoint: ${OSS_ENDPOINT}
    url: ${OSS_URL}
    bucket: ${OSS_BUCKET}
    access-key-id: ${AL_ACCESS_KEY}
    access-key-secret: ${ALIBABA_ACCESS_KEY_SECRET}

spring:
  application:
    name: account-svc
  elasticsearch:
    rest:
      uris: ${ES_REST_URL}
  data:
    mongodb:
      uri: ${MONGODB_URL}
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: ${ES_CLUSTER_NAME}
      cluster-nodes: ${ES_CLUSTER_NODE}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    timeout: ${REDIS_TIMEOUT:3000}
    password: ${REDIS_PASSWORD}
  cloud:
    alibaba:
      seata:
        tx-service-group: ${SEATA_TX_GROUP}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${ACCOUNT_DATASOURCE_URL}
    username: ${ACCOUNT_DATASOURCE_USERNAME}
    password: ${ACCOUNT_DATASOURCE_PASSWORD}
    druid:
      initial-size: ${DRUID_INITIAL_SIZE:5}
      min-idle: ${DRUID_MIN_SIZE:5}
      max-active: ${DRUID_MAX_SIZE:10}
      max-wait: ${DRUID_MAX_WAIT:6000}
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      exception-sorter: true
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        login-username: ${DRUID_LOGIN_USERNAME}
        login-password: ${DRUID_LOGIN_PASSWORD}
  jpa:
    database: MYSQL
    show-sql: off
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      file-size-threshold: 10485760
      max-file-size: 1MB
  mvc:
    throw-exception-if-no-handler-found: true

jasypt:
  encryptor:
    password: 88ff3c4b1c88a44f974ad01c7a8f36d63717edf13ea528ba2bccb9c41a4fb812cef1465182041c8701e7db08a889358faf7603e975c7d2dad9d33eecabd271f3
